---
title: "SDS 4135 - Project 2"
subtitle: "Due "
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Grand Ave Bus Time Analysis

Joseph Silagi from St. Louis Metro has provided us with one year of data
from the #70 Grand Ave Bus line. Each row of the data contains information from
one stop from one trip of a bus driving the route, and there are rows for both the
northbound (route_direction_id = 7) and the southbound (route_direction_id = 9)
routes.  Each row contains information about the time of day (in seconds after
midnight) that the bus arrived, how early or late it was (adherence) how many
people boarded, how many people exited (alightings), and various other pieces
of information, such as which physical bus the data came from.

You will notice that the arrival and departure times are often missing, which 
means that the adherence is missing as well. The overall task of this project
is to fill in those missing values. In addition to the missing values in the original
dataset, marked as NA, I have marked additional rows as NA for evaluating your
method of filling them in. Part of your grade will depend on your overall RMSE
for filling in the missing values.

Below is a list of items you are expected to address in your report:

1. Figure out the sequence of stops in the northbound and southbound directions

2. Investigate how the time of the the stop (departure time - arrival time) depends
   on various factors, such as stop, boardings, alightings, time of day, etc.

3. Create a model or method for filling in the missing arrival times, departure times,
   and adherences. Explain in detail how you filled in the missing times.

4. Return a dataset with filled in times, in the following order: order by trip, with
   trips ordered by departure time of the first stop in the trip. Within trip, order
   chronologically.





