---
title: "SDS 4135 - Project 1"
subtitle: "Due 5PM Sunday September 6"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# NFL season predictions

Your task is to predict the entire 2026 NFL regular season by providing probabilities
for the winner of every game. You will turn in a .csv file with
your probabilities using the template that I provide.

To help build your probabilities, I have provided a dataset with the outcomes
of the last 11 NFL regular seasons. Note that, starting in 2021, the NFL switched
from a 16-game to a 17-game regular season. I have also provided a dataset
with the results of the playoffs for these 11 seasons. 

In building your predictions, you are free to use any external sources you wish.
However, in your report, I would like you to present at least one analysis that 
uses only the data I have provided. If you use external sources, please write
about them in your report.

# Datasets

Datasets were downloaded from www.pro-football-reference.com. See for
example:

https://www.pro-football-reference.com/years/2025/

That page has a glossary explaining each column in the dataset. The year column
in the regular season standings dataset refers to the year in which the season
started (typically late summer). The playoffs occur after the regular season,
usually after January 1. This means that if a playoff game has a date in
January of 2024, this is a game from the playoffs following the 2023 regular
season.

Note that a few teams have changed names during the past 10 years:

St. Louis Rams --> Los Angeles Rams

Oakland Raiders --> Las Vegas Raiders

Washington Redskins --> Washington Football Team --> Washington Commanders

San Diego Chargers --> Los Angeles Chargers

# Scoring

The projects will be scored using the log score metric. Let $w_i$ encode the outcome
of the $i$th of $n$ games, with $w_i = 0$ if the away team wins, $w_i = 1$
if the home team wins. Let $p_{i,j}$ be
the probability that you assign to outcome $j \in \{0,1\}$, such that $p_{i,0} + p_{i,1} = 1$ for each game $i$. The log score uses the probability that you assign to the 
actual outcome:

$$\mbox{log score} = \sum_{i=1}^n \log p_{i,w_i}$$.

In the event of a tie in game $i$, the contribution to the log score will be:

$$\frac{1}{2}\log p_{i,0} + \frac{1}{2} \log p_{i,1}.$$

You are rewarded for assigning high probability to the events that actually occur. For ties, you are rewarded for assigning probabilities close to 1/2. This metric will allow us to keep track of everyone's performance throughout the
semester as the season proceeds. 
